---
# Clone the Adafruit Python DHT library for the DHT11/DHT22 humidity sensor and install it
- name: Clone Adafruit Python DHT repository
  git: repo=https://github.com/adafruit/Adafruit_Python_DHT.git
       dest="/home/pi/project/Adafruit_Python_DHT"
       clone=yes
- name: Install the Adafruit Python DHT library
  command: python setup.py install chdir="/home/pi/project/Adafruit_Python_DHT"
