---
- name: Reboot the device
  command: reboot
  async: 0
  poll: 0
  ignore_errors: true
- name: Wait for device to start
  local_action: wait_for host="{{ newdevice_hostname }}.local" port=22
                state=started
  sudo: false
